apiVersion: v1
kind: ConfigMap
metadata:
  namespace: "{{ .Values.product }}-{{ .Values.tenant }}-{{ .Values.group }}"
  name: config-app-{{ required "An app name is needed" .Values.app | replace "." "-" }}
  labels:
    app: {{ template "bz-api.name" . }}
    chart: {{ template "bz-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    product: {{ .Values.product }}
    environment: {{ .Values.environment }}
    tenant: {{ .Values.tenant }}
    group: {{ .Values.group }}
data:
  config.app.yaml: {{ toYaml .Values.appConfig | quote}}
