{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bz-api.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "{{ .Values.product }}-{{ .Values.tenant }}-{{ .Values.group }}"
  name: ingress-{{ $fullName }}
  labels:
    app: {{ template "bz-api.name" . }}
    chart: {{ template "bz-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    product: {{ .Values.product }}
    environment: {{ .Values.environment }}
    tenant: {{ .Values.tenant }}
    group: {{ .Values.group }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - http:
      paths:
      - path: {{ $ingressPath }}
        backend:
          serviceName: "svc-{{ $fullName }}"
          servicePort: http
{{- end }}
