{{- $fullName := include "bz-api.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: "{{ .Values.product }}-{{ .Values.tenant }}-{{ .Values.group }}"
  name: ingress-{{ $fullName }}-health
  labels:
    app: {{ template "bz-api.name" . }}
    chart: {{ template "bz-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    product: {{ .Values.product }}
    environment: {{ .Values.environment }}
    tenant: {{ .Values.tenant }}
    group: {{ .Values.group }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /health
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: "/{{ .Values.tenant }}/{{ .Values.app }}/health"
        backend:
          serviceName: "svc-{{ $fullName }}"
          servicePort: health
      - path: "/{{ .Values.tenant }}/{{ $fullName }}/health"
        backend:
          serviceName: "svc-{{ $fullName }}"
          servicePort: health
